triggers:
  - description: null
    envs: []
    last_enabled_at: 2024-05-16 10:01:21.342116+00:00
    name: Real-time predictions
    pipeline_uuid: predict
    schedule_interval: null
    schedule_type: api
    settings: null
    sla: null
    start_time: 2024-05-16 10:00:00+00:00
    status: active
    token: ef46ef6d89f44853b3d31ef771991bc5
    variables: {}
