AWS_REGION="eu-north-1"

# Dynamically generated by TF
export MODEL_BUCKET_PROD="stg-mlflow-models-dara-mental-health-project"
export PREDICTIONS_STREAM_NAME="stg_ride_predictions-mental-health-project"
export LAMBDA_FUNCTION="stg_prediction_lambda_mental-health-project"

# Model artifacts bucket from the previous weeks (MLflow experiments)
export MODEL_BUCKET_DEV="mlflows-artifacts-remote"

# Set RUN_ID. Ideally, we get RUN_ID with best performance from latest experiments in MLflow
export RUN_ID="57342ae687254eeeac28602bb8d42aca"

# NOT FOR PRODUCTION!
# Just mocking the artifacts from training process in the Prod env.
# Remember that prod(and also staging bucket) are destroyed together with other resources by Terraform
aws s3 sync s3://${MODEL_BUCKET_DEV} s3://${MODEL_BUCKET_PROD}

# Set new var RUN_ID in existing set of vars.
variables="{PREDICTIONS_STREAM_NAME=${PREDICTIONS_STREAM_NAME}, MODEL_BUCKET=${MODEL_BUCKET_PROD}, RUN_ID=${RUN_ID}}"

# https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html. We increased the timeout time due to the time taken for loading nltk
aws lambda update-function-configuration --function-name ${LAMBDA_FUNCTION} --environment "Variables=${variables}" --timeout 30
